[options]
db_host = False
db_port = False
db_user = odoo
db_password = odoo
db_name = restaurant_management
addons_path = C:/Users/ith/PycharmProjects/restaurant/restaurant_base/addons,
              C:/Users/ith/PycharmProjects/restaurant/restaurant_base/odoo/addons,
              C:/Users/ith/PycharmProjects/restaurant/custom_addons

bin_path = C:/Program Files/wkhtmltopdf/bin
wkhtmltopdf = C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe
